stages:
  - install
  - test

install_dependencies:
  stage: install
  image: python:3.11
  script:
    - echo "Installing Python dependencies..."
    - pip install --upgrade pip
    - pip install -r requirements.txt

run_tests:
  stage: test
  image: python:3.11
  script:
    - echo "Running Python tests..."
    - pytest .
  dependencies:
    - install_dependencies
